### PR TITLE
Read .env variables from file

### PR DESCRIPTION
**Pull request by hannah-bulmer**
Before, environment variables were expected to be stored in a `.env` file located in your computers home directory.

I have moved the to be stored in a file beside the fixture called `test/.globalEnv`. if this is not a good name for a file, please suggest because there might be a better place to store it. I think calling it `.env` might be confusing, as its contents/context could get mixed up with the action `.env` file.

### CODE REVIEW

**Comment by dvd-z** [comment]
Is it OK to make it into a JSON or something?

**Comment by hannah-bulmer** [comment]
It currently has to be a `.env` file, does a JSON make more sense? I thought they would be read from a `.env` type file because they are environment variables

**Comment by dvd-z** [comment]
It feels a bit weird having global variables inside a ".env" file. Also if we ever do end up having real environment variables in this project we'd have to make sure there were no collisions / `process.env` doesn't get polluted one direction or the other.

**Comment by hannah-bulmer** [comment]
Hmm...the problem with the global variables though is regardless, they would have to be added to process.env since in the action/trigger they would be called with process.env. So I don't think we could avoid that "pollution". There are a limited number of global variables available to use, so they would just have to be reserved for adding to this project in the future.

Also, the global variables are very platform-specific, so I don't think they would accidentally end up being needed in the CLI too.

**Pull request merged**
